# Generated by Django 5.1.3 on 2024-11-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_link_image_alter_link_button_text_alter_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='button_text',
            field=models.CharField(default='Bấm vào đây để gặp lễ tân', max_length=255, verbose_name='Nội dung nút bấm'),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên (viết liền không dấu)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(default='Nhắn cho em để set kèo', max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(verbose_name='Mỗi link cách nhau 1 dấu,'),
        ),
    ]
